# Generated by Django 5.1.2 on 2024-11-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Product', '0002_alter_product_options_alter_product_active_and_more'),
        ('EShop_products_category', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='EShop_products_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
