# Generated by Django 5.1.5 on 2025-02-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0003_alter_profile_options_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
