# Generated by Django 5.1.5 on 2025-02-06 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0007_receiver_profile_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('address1', models.TextField(verbose_name='آدرس اول')),
                ('address2', models.TextField(blank=True, null=True, verbose_name='آدرس دوم')),
                ('postal_code', models.PositiveIntegerField(verbose_name='کدپستی')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('mobile', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('emergency_call', models.CharField(max_length=15, verbose_name='شماره تماس اضطراری')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اطلاعات پروفایل',
                'verbose_name_plural': 'پروفایل کاربران',
            },
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
