# Generated by Django 5.1.5 on 2025-02-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0008_userprofile_delete_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'عکس پروفایل', 'verbose_name_plural': 'عکس پروفایل کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'اطلاعات پروفایل', 'verbose_name_plural': 'اطلاعات پروفایل کاربران'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='family_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
