# Generated by Django 5.1.5 on 2025-02-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0009_alter_profile_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='emergency_call',
            new_name='Emergency_call',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address2',
        ),
    ]
