# Generated by Django 5.1.5 on 2025-02-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0010_rename_emergency_call_userprofile_emergency_call_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address1',
            new_name='address',
        ),
    ]
