# Generated by Django 5.1.5 on 2025-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0011_rename_address1_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Emergency_call',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس اضطراری'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کدپستی'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='استان'),
        ),
    ]
