# Generated by Django 5.1.5 on 2025-02-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Order', '0005_alter_order_gateway_name_alter_order_status'),
        ('EShop_account', '0012_alter_userprofile_emergency_call_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping_FullName', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی گیرنده:')),
                ('Shipping_Address', models.TextField(verbose_name='آدرس گیرنده:')),
                ('Shipping_Mobile', models.TextField(verbose_name='موبایل گیرنده :')),
                ('Shipping_PostalCode', models.PositiveIntegerField(max_length=15, verbose_name='کد پستی گیرنده :')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop_account.userprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop_Order.order')),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EShop_Order.orderdetails')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور های موجود',
            },
        ),
    ]
