# Generated by Django 5.1.5 on 2025-02-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0013_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Is_send',
            field=models.BooleanField(default=False, verbose_name='ارسال شده/نشده'),
        ),
    ]
