# Generated by Django 5.1.5 on 2025-02-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0014_invoice_is_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Shipping_Mobile',
            field=models.CharField(max_length=15, verbose_name='موبایل گیرنده :'),
        ),
    ]
