# Generated by Django 5.1.5 on 2025-02-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0017_remove_invoice_order_details_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Shipping_Address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس گیرنده:'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Shipping_FullName',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی گیرنده:'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Shipping_Mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='موبایل گیرنده :'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Shipping_PostalCode',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کد پستی گیرنده :'),
        ),
    ]
