# Generated by Django 5.1.5 on 2025-02-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0018_alter_invoice_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Shipping_PostalCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی گیرنده :'),
        ),
    ]
