# Generated by Django 5.1.5 on 2025-02-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0019_alter_invoice_shipping_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کدپستی'),
        ),
    ]
