# Generated by Django 5.1.5 on 2025-02-24 11:53

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0020_alter_userprofile_postal_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('order_item', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='order',
            new_name='orderItem',
        ),
    ]
