# Generated by Django 5.1.5 on 2025-02-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_account', '0021_alter_invoice_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='orderItem',
            new_name='order',
        ),
    ]
