# Generated by Django 5.1.2 on 2025-01-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_us',
            field=models.TextField(blank=True, null=True, verbose_name='درباره ما'),
        ),
    ]
