# Generated by Django 5.1.2 on 2025-01-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Settings', '0002_sitesettings_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='fax',
            field=models.CharField(max_length=50, verbose_name='فکس'),
        ),
    ]
