# Generated by Django 5.1.2 on 2025-01-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Settings', '0003_alter_sitesettings_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='mobile',
            field=models.CharField(max_length=50, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='تلفن'),
        ),
    ]
