# Generated by Django 5.1.2 on 2025-01-04 06:18

import EShop_Settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Settings', '0004_alter_sitesettings_mobile_alter_sitesettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=EShop_Settings.models.upload_settings_image_path, verbose_name='لوگرسایت'),
        ),
    ]
