# Generated by Django 5.1.2 on 2025-01-04 06:20

import EShop_Settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Settings', '0005_sitesettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=EShop_Settings.models.upload_settings_image_path, verbose_name='لوگو سایت'),
        ),
    ]
