# Generated by Django 5.1.2 on 2025-01-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس های کاربران'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده /نشده'),
        ),
    ]
