# Generated by Django 5.1.2 on 2024-11-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی محصولات', 'verbose_name_plural': 'دسته بندی محصولات'},
        ),
    ]
