# Generated by Django 5.1.2 on 2024-12-19 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Sliders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'اسلایدر', 'verbose_name_plural': 'اسلاید ها'},
        ),
    ]
