# Generated by Django 5.1.2 on 2025-01-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
