# Generated by Django 5.1.2 on 2025-01-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Order', '0002_alter_order_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Trc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد پیگری'),
        ),
        migrations.AddField(
            model_name='order',
            name='cartNumber',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='وضعیت پرداخت'),
        ),
    ]
