# Generated by Django 5.1.2 on 2025-01-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Order', '0003_order_trc_order_cartnumber_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='GateWay_name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='نام درگاه پرداخت'),
        ),
    ]
