# Generated by Django 5.1.2 on 2025-01-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EShop_Order', '0004_order_gateway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='GateWay_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وضعیت پرداخت'),
        ),
    ]
